### ISSUE TITLE
Complex model with nested loops

### ISSUE THREAD

**Issue by vanquss** [egonl/SharpDocx#1]
I have not found a way to achieve repetition for all the elements defined within the first root loop eg. texts, tables (nested loops). <% AppendParagraph (); %> does not seems to work when content within root loop is complex. Am I missing something? Is it possible with this library to achieve this?

**Comment by egonl** [comment]
SharpDocx 2.0 does support nested loops/content and is currently in beta. See attached Tutorial.cs.docx under 'Combining loops, text blocks and tables'. Tutorial.docx contains the generated document. Is that similar to what you want to achieve?
[Tutorial.cs.docx](https://github.com/egonl/SharpDocx/files/2531576/Tutorial.cs.docx)
[Tutorial.docx](https://github.com/egonl/SharpDocx/files/2531578/Tutorial.docx)

**Comment by vanquss** [comment]
Yes. Thank you.
Besides this thing the library is working very well. Great job!
I'm looking forward for the next release then :)

**Comment by egonl** [comment]
@weiterleiter1981 Added the branch 'v2'. See Tutorial.cs.docx for examples. It's still a work in progress, so things might change a bit.

**Comment by egonl** [comment]
Merged v2 in master and deleted the v2 branch.
