### ISSUE TITLE
Repeating a table multiple times in a foreach loop

### ISSUE THREAD

**Issue by darindragomirow** [egonl/SharpDocx#10]
Hello, Im not sure if i am not repeating the same issue as some of the others, but i cant find a way to generate a table multiple times in a foreach loop.
I have for example : 
<% foreach(var child in Model.Children) {%> 
A Table with multiple columns:[child.Property1][child.Property2][child.PropertyN]
<% } %>
I want to generate a separate table for each child and filled it with the child properties.
Is this achievable in version 2?

**Comment by egonl** [comment]
This is possible in V2, see https://github.com/egonl/SharpDocx/raw/v2/Samples/Views/Tutorial.cs.docx under 'Combining loops, text blocks and tables' and 'Loops, tables and the AppendRow method'.

**Comment by delianjekov** [comment]
@egonl, I am not sure that what you refer to in the document describes the use case pointed out in the comment of the issue. In the document it's described how to combine/nest loops and how to append rows to table. But it does not say how to achieve the most simple case. I'm having the very same issue. So let me paraphrase the question. Is it possible to iterate over a collection of objects and create a new separate table (preferably each table on a new page) for every element in the collection, where every table (page) is populated with the properties of the current item in the loop. For example, let's say we've got a list of students. Each student has some properties and attends certain classes. Is it possible to create a document, where for each student, there will be a separate table on a new page and in that table, there will be let's say the student's names, age, id and maybe some grades for the classes they attend?

**Comment by egonl** [comment]
[Here](https://www.dropbox.com/s/o03k1lxy4apnkvb/Model.cs.docx?dl=0)? is a slighly modified Model.cs.docx from v2, which generates a table for each country on a new page. Basically I removed AppendRow and {!. Also, I added a Page Break with a space right in front of it, so it won't get deleted.

**Comment by delianjekov** [comment]
It still does not seem to work. It only prints the last element in the collection.

**Comment by darindragomirow** [comment]
This is not working in branch "v2".Im using the test project "Model" in the repo and replace the old Model.cs.docx with that you've attached.
Should we use another branch?

**Comment by egonl** [comment]
I just downloaded v2, replaced Model.cs.docx and ran the Model project.  [This](https://www.dropbox.com/s/ny0gvmo0xcpdta8/Model.docx?dl=0) is the output and it is what I expect it to be. Is your output different?

**Comment by delianjekov** [comment]
Ok my bad for not directly downloading the repository and building from sources. It appears that the v1.2 nuget package that's published is from your repo, the master branch and the v2 nuget package is from a fork that has a couple of commits on top of your v2 branch that broke the for loop. Is there any chance that you publish a v2 nuget package?

**Comment by egonl** [comment]
v2 package is now available on nuget.org.
