### ISSUE TITLE
DivideByZeroException on some Bitmaps

### ISSUE THREAD

**Issue by slichte** [egonl/SharpDocx#14]
Hi!

I use SharpDocx for creating some Word docs including images based on templates from a .NET Core webservice. In general it works just fine, really good work!

Sometimes, however, I get a DivideByZeroException when certain Bitmaps are to be included into the doc. I did some debugging and found out that these Bitmaps do not set their horizontal and vertical pixels per meter in their BITMAPINFOHEADER. So the following code fragment fails:

https://github.com/egonl/SharpDocx/blob/59486fff775bdad4ab13e7762428da04600f1792/SharpDocx/ImageHelper.cs#L65-L67

I could not fully determine wether the props in BITMAPINFOHEADER are required to be non-zero by specification, but if you manually import the files into a Word document, there is no problem.

Maybe default values for horzRezDpi and vertRezDpi would be useful?

Thanks and have a nice day!

**Comment by egonl** [comment]
Good point. I added a fix for this in 2.0.2. Can you give it a try?

**Comment by slichte** [comment]
Just tested 2.0.2 with my application and it works like a charm! Thanks a lot for your effort!
