### ISSUE TITLE
Issue with if statement

### ISSUE THREAD

**Issue by arnederuwe** [egonl/SharpDocx#17]
I'm having an issue with generating the following template:
```
Report Info - <%=Model.Id%> - <%=Model.CustomerName%>
Some standard text here

<% if (Model.Contacts.Count > 0) { %>

Some text providing additional info about a table

(this is a table in word)
<% foreach (var c in Model.Contacts) { %>
Email	AreaId
<%=c.Email1%>	<%=c.AreaId%><% AppendRow(); %>
(the table ends here)
<% } %>
<% } %>

Generated on <%=DateTime.Now%>
```

This fails with:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpDocx.CodeBlocks.TextBlock.GetBody(OpenXmlElement startText, OpenXmlElement endText)
   at SharpDocx.CodeBlocks.TextBlock.Initialize()
   at SharpDocx.CodeBlockBuilder.AddCodeBlocks(CharacterMap map)
   at SharpDocx.CodeBlockBuilder..ctor(WordprocessingDocument package)
   at SharpDocx.DocumentCompiler.Compile(String viewPath, String className, String baseClassName, Type modelType, List`1 usingDirectives, List`1 referencedAssemblies)
   at SharpDocx.DocumentAssembly..ctor(String viewPath, Type baseClass, Type modelType)
   at SharpDocx.DocumentFactory.Create(String viewPath, Object model, Type baseClassType, Boolean forceCompile)
```

The problem has to do something with the if statement, removing the statement or writing it like this works fine:
```
<% if (Model.Contacts.Count > 0) {  foreach (var c in Model.Contacts) { %>
```
Problem is that I can't prepend text that way.

Also important to mention, it renders just fine on 1.2.1, I'm only getting the error in 2.0.2.

Thank you for building this, if you need more info please let me know.

**Comment by egonl** [comment]
Looking good, you just forgot an exclamation mark, as in `<% foreach (var c in Model.Contacts) {! %>`. The exclamation mark tells SharpDocx 2 that the loop does NOT contain a repeatable text block. SharpDocx will render the text block only once, execute the loop and AppendRow will append rows to the table. 

Text blocks -and exclamation marks to prevent them from repeating- are new features in version 2. SharpDocx 1.2.1 would only loop, which gave the result you expected.

The exclamation mark is a bit strange, but I couldn't come up with something better. Sometimes you want text blocks, sometimes you don't. And once you know what that exclamation mark does, things become easier to understand.

**Comment by arnederuwe** [comment]
Thanks for the explanation! I was basing my code off an old Model.cs.docx so it seems, where the '!' wasn't present.
All cleared up now, works perfectly
