### ISSUE TITLE
Text / cell color

### ISSUE THREAD

**Issue by slimshader** [egonl/SharpDocx#2]
Hi,

first: fantastic library, a lifesaver! My questions:
1. doc template has some of table cells backgrounds different colors depending on resulting text (succeed, failed) red/green/orange etc. How to fill cell with different color (from set of colors) depending of variable value
2. same question for text color: depending on variable value, text will have one of predefined colors, how to  change the color of the text

**Comment by egonl** [comment]
Thanks. You could do this by defining your own document class and add methods to set the cell or text color. E.g. in the Inheritance sample you could add these two methods to MyDocument: 
```
	protected void SetCellColor(string color)
	{
		var cell = CurrentCodeBlock.Placeholder.GetParent<TableCell>();
		if (cell == null) return;
		cell.TableCellProperties.Shading = new Shading
		{
			Fill = color,
			Color = "auto",
			Val = new EnumValue<ShadingPatternValues>(ShadingPatternValues.Clear)
		};
	}

	protected void SetTextColor(string color)
	{
		var run = CurrentCodeBlock.Placeholder.GetParent<Run>();
		if (run == null) return;
		run.RunProperties.Color = new Color { Val = color };
	}
````
Add a table in Inheritance.cs.docx and paste this in a table cell to make that cell green:
```
    <% SetCellColor("00FF00"); %>
```
And use this for setting the text color of the current run to red:
```
<% SetTextColor("FF0000"); %>
```

**Comment by slimshader** [comment]
Thanks for your help I have problem tho GetParent<> generic method does not seem to exist. My case is simple: in the model I have int value and based on that value text has to be in different color. Does it make more sensie to add if / else logic to the view or just add a method to a derived document that will set it within a method?

**Comment by egonl** [comment]
Add this to MyDocument and it should compile just fine:
```C#
using DocumentFormat.OpenXml;
using SharpDocx.Extensions;
 ```
I prefer to keep views dumb, but you have to decide for yourself.

**Comment by apetrut** [comment]
Hi @egonl , I tried to put <% SetCellColor("00FF00"); %> inside a table cell but I got an error saying: The name 'SetCellColor' does not exist in the current context. 

What I want is to use a custom written method inside the table cell that will take 2 string params and color the text based on those params.

It seems now that SharpDocx only supports using SetTextColor as method name.
Can you please advice?

Regards.
