### ISSUE TITLE
Two if statements beneeth each other causes a weird bug

### ISSUE THREAD

**Issue by programmingworld1** [egonl/SharpDocx#20]
Below code works, but when the second if statement is true and first not, it shows an empty space at the first line.

<% if (we.EndDate == default(DateTime)) { %>Heden<% } %>

<% if (we.EndDate != default(DateTime)) { %> <%= we.EndDate.Year%> <% } %>

So I removed the new line:
<% if (we.EndDate == default(DateTime)) { %>Heden<% } %>
<% if (we.EndDate != default(DateTime)) { %> <%= we.EndDate.Year%> <% } %>

This causes a very weird behaviour where nothing is shown, they are only shown at the last element from the for loop...

**Comment by egonl** [comment]
I just fixed issue #18 and I think this also fixes your issue. Could you verify this? NuGet package 2.0.3 includes the fix.
