### ISSUE TITLE
If Statements in Loop only Correct for First Item (2.0.4)

### ISSUE THREAD

**Issue by paulsterling** [egonl/SharpDocx#25]
In the case where there is an If statement in a loop, the first item's If statement is evaluated correctly, but all others appear to ignore the statement. Taking the below snippet, where Show is bool property for each item in the collection (I've omitted the table markup here, but this is in a table and uses `AppendRow();`):

```
<% foreach (var item in Model.Collection) {! %>
    <%if(item.Show) {%> Content <%}%>
<%}%>
```

If `item.Show == false` for all items, the first item will not be written, but all others will be.  It looks like there were some fixes around a related issue (#18) but this seems a different behavior. 

There is another odd behavior with Id statement in Loops - in the case above, if `item.Show == true` for the first item, the "Content" text will be written as many times as there are items in the collection, but all at the insertion point for the first item. From that point on, all other If statements are ignored as above. So the output looks like:

Content
Content
Content
Content
...etc...

I'd be happy to work on PR for this if there is any guidance @egonl might provide.

**Comment by egonl** [comment]
You're mixing text blocks and AppendRow. That won't work. Prevent a text block with an exclamation mark:

```<% if (item.Show) {! %>Content: <%= item.Name %> <% AppendRow(); } %>```

The tutorial isn't very clear about this and should be updated.

If you're still having issues with for loops, if statements and AppendRow, please send me a sample, e.g. a modified Model project. I had some difficulties recreating what you experienced.

**Comment by paulsterling** [comment]
Hi @egonl -

It is hard to explain. I've done my best to demonstrate the behavior in this repo ([https://github.com/paulsterling/SharpDocxIfLoop](https://github.com/paulsterling/SharpDocxIfLoop)). The last table in the template Docx is the one with the behavior matching what I (tried) to describe above.

Thank you for offering to have another look and please let me know if I can provide any additional information.

**Comment by egonl** [comment]
Thanks for the repo. You did indeed mix text blocks and AppendRow:

```<%if (item.ShowText) {%>You can see me because I’m true<% } AppendRow(); %>```

This won't work. When you're using AppendRow, use the Write-method (or <%= ... %>), e.g.:

```<%if (item.ShowText) { Write("You can see me because I’m true"); } AppendRow(); %>```

See the attached [IfLoopTests.cs.docx](https://github.com/egonl/SharpDocx/files/5233999/IfLoopTests.cs.docx).

What you wrote seems logical and it would be nice if it worked that way. However, it doesn't. Text blocks are a 2.0 feature and AppenRow/AppendParagraph a 1.0 feature. You're the first one that I know of that tried to mix them, I never thought of mixing them. Now I do.

**Comment by paulsterling** [comment]
Thanks for clarifying. That makes perfect sense and I see how to use these together now.

Closing this issue as I believe the solution is now clear. Thank you!
