### ISSUE TITLE
SharpDocx/SharpDocx/CodeBlocks/TextBlock.cs  Line71-75 has a bug

### ISSUE THREAD

**Issue by cnraorong** [egonl/SharpDocx#26]
SharpDocx/SharpDocx/CodeBlocks/TextBlock.cs,   when nextElement.NextSibling() is null, the program will crash.....

**Comment by cnraorong** [comment]
add some codes like next,   successful   ...  :)
if (nextElement == null)  { break;  }

**Comment by egonl** [comment]
I tried to reproduce this, but without success. Do you have an example view for me?

**Comment by egonl** [comment]
Can't reproduce, reporter afk. Closing issue.
