### ISSUE TITLE
"If (XXX) {} else {}" syntax in the.cs.docx template file there are some problems

### ISSUE THREAD

**Issue by cnraorong** [egonl/SharpDocx#27]
“if(xxx) {} else {}” syntax is not supported in the.cs.docx template file

"If (XXX) {} if(yyy) {}" syntax can work normally

**Comment by egonl** [comment]
This is not a bug but a design decision. It's briefly mentioned in the Tutorial under Conditional content/Text block limitations/3. It's also on the 'nice to have list'.
