### ISSUE TITLE
Exception of type 'SharpDocx.SharpDocxCompilationException' was thrown.

### ISSUE THREAD

**Issue by IT-VBFK** [egonl/SharpDocx#29]
Hi,

If I export a word document with a view model, I always encounter this error. It doesn't really matter what I do.. 

See this test project, compile and see the error (export.cs:14).
[testSharpDocx.zip](https://github.com/egonl/SharpDocx/files/5495897/testSharpDocx.zip)

What I am doing wrong here? 

Thanks for hints.

btw: it is completely irrelevant if I replace the "Model" in the Model.cs.docx with "ViewModel". Both are not working...

**Comment by egonl** [comment]
There were a couple of problems with your solution.
- You took the example Model.cs.docx, but used a different view model in another namespace. That's not working. 
- The view was using some methods not present in your solution. I commented those method calls out.
- Also, the view was refering to your class (ViewModel), and not to an instance of it (the Model field). Always use Model.
- And last but not least you didn't use the SharpDocx IDE for troubleshooting. 

Here's a working version of  your solution: [testSharpDocx_fixed.zip](https://github.com/egonl/SharpDocx/files/5525134/testSharpDocx_fixed.zip)

**Comment by IT-VBFK** [comment]
Ahh I see.

Thank you for your help!
