### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by migill** [egonl/SharpDocx#3]
This project is an impressive piece of work. I've tried various libraries (and written some of my own) for Word document production, and liked none of them as much as I do this one. Kudos to you.

Anyway, I'd like to use it in a .NET Core solution. I don't even know if this is possible?

**Comment by egonl** [comment]
Thanks. I just commited a version with partial support for .NET Standard 2.0. The support is partial because the ImageHelper is still using System.Windows.Media.Imaging, which isn't available in .NET Standard. I'll fix that later.

The Model and Inheritance samples now also build a .NET Core 2.0 application, which uses the .NET Standard version of SharpDocx. I don't use .NET Core much atm, but the samples seem to work OK. Please let me know if there are any issues.

**Comment by migill** [comment]
Excellent, thanks. (I've converted my project to .NET Framework for now, but I'll convert back if you happen to get to 100% on the .NET Standard side).

**Comment by egonl** [comment]
There's no nuget package with support for .NET Standard atm. I'll release SharpDocx 1.2 as soon as .NET Standard support is complete.

**Comment by weiterleiter1981** [comment]
Ah..thats .great... I guess I will keep going with included and referenced Project and remove it, when nuget is available.

I will also need image processing... Quite possible that  I will try to implement it...should i send a request in case i am doing something or doesnt make it sense?

**Comment by egonl** [comment]
Added support for inserting images (bmp/gif/png/jpeg/tif) under .NET Standard 2.0. I'll have a look at the namespace-issues next. When that's fixed .NET Standard 2.0 support should be more or less complete.

@weiterleiter1981 Nested loops/logic are not really well supported in this version of SharpDocx, see issue #1.

**Comment by egonl** [comment]
All System.* and Microsoft.* DLL's are now automatically referenced in .NET Standard 2.0. Also, the tutorial now works as a .NET Core app as well. Let me know if there are any .NET Core issues left. If everything seems OK I'll release 1.2.

**Comment by weiterleiter1981** [comment]
Images seem to be fine. Dll loading seems to work as well, as far as i can tell by now.

Am hardly waiting for nested loop support :-)))

**Comment by migill** [comment]
.NET Standard version works for me in my .NET Core project - thanks! Looking forward to being able to pull it via NuGet...

**Comment by egonl** [comment]
Just released version 1.2.0 of SharpDocx. Install with ```Install-Package SharpDocx -Version 1.2.0```.

**Comment by migill** [comment]
Worked first time - fantastic, thanks again!
