### ISSUE TITLE
Insert image from bitmap

### ISSUE THREAD

**Issue by Vitaly1025** [egonl/SharpDocx#30]
I want dynamically generate image and without saving, insert in document. It's possible?

**Comment by mitnick2012** [comment]
I have the same issue, need to upload base64 string image directly to the docx file

**Comment by mitnick2012** [comment]
I worked on that and made a feature to add image from base64 string variable using Image64(base64stringVariable)
send pull request  and wait for the author of this repository to update it

**Comment by egonl** [comment]
Version 2.4.0 now has ImageFromBase64, ImageFromUrl and ImageFromStream methods.
