### ISSUE TITLE
images result in height/width zero (.NET Standard 2.0)

### ISSUE THREAD

**Issue by sethzollinger** [egonl/SharpDocx#34]
Small images are invisible if either their height or width is below its dpi value, when calculating the new values.

This only occurs in non `NET35 || NET45` targets because `BitmapImage` uses `double` for its dpi property while `ImageInfoBase` uses `int` resulting in a zero result fater a divison.

I suggest casting the dpi to `double`:
https://github.com/egonl/SharpDocx/blob/v2.0.2/SharpDocx/ImageHelper.cs#L62

**Comment by egonl** [comment]
Released fix in version 2.1.0.
