### ISSUE TITLE
"Whitespace" being swallowed by Text Blocks

### ISSUE THREAD

**Issue by cedwards-telis** [egonl/SharpDocx#36]
Hi- thanks for a great project I think this is going to be really useful for us.

Whenever I have a text block any empty paragraphs or page breaks are removed in the generated document?

I hope you can catch this meaning below.

i.e. Test.cs.docx

<% if(true) { %>
1
2
[Paragraph Break]
3
[Page Break]
<%}%>

Generates
Test.docx
1
2
3

Is this expected behaviour?

**Comment by cedwards-telis** [comment]
I have isolated this issue down to a code block starting at line 34 of Appender.cs.  This code block contains a comment "Ignore empty paragraphs" so I assume this is deliberate.  Given that it's page breaks that I want preserved and I don't care about paragraph breaks and there might be a good reason for it I have changed the code from

`                if (element.HasText())
                {
                   //Ignore empty paragraphs.
                   insertionPoint = insertionPoint.InsertAfterSelf(element);
                }`

To

`                if (element.HasText() || element.Descendants<Break>().Any())
                {
                   //Ignore empty paragraphs.
                   insertionPoint = insertionPoint.InsertAfterSelf(element);
                }`

**Comment by egonl** [comment]
Released fix in version 2.1.0.
