### ISSUE TITLE
WebServer integration (IIS) and view autoupdate on file change

### ISSUE THREAD

**Issue by PravdaJan** [egonl/SharpDocx#38]
**DocumentCompiler.Compile method**

- using of Path.GetTempPath() fails under IIS appliation in isolation mode as the directory is not accessible by AppPool identity
- using temp file would be nice only under #if DEBUG precompiler block

**Namespaceless classes - WebForms**

- if Model class is defined withing App_Code without namespace definition, following code will generate "using ;"

```
if (modelType != null)
{
  // Add namespace(s) of Model and reference Model assembly/assemblies.
  foreach (var type in GetTypes(modelType))
  {
    **usingDirectives.Add($"using {type.Namespace};");**
    referencedAssemblies.Add(type.Assembly.Location);
  }
}
```

**DocumentFactory.Create method**

- checking FileInfo.LastWriteTime for already created classes will be helpful in the case of View gets changed under running application
- workaround is to check LastWriteTime when Creating proxy class and setting forceCompile to true if file is newer

**Comment by egonl** [comment]
Good suggestions, I've implemented them all: see release 2.2.0.
