### ISSUE TITLE
Is it possible to assemble documents?

### ISSUE THREAD

**Issue by remesq** [egonl/SharpDocx#43]
Is there a relatively easy way to combine two or more documents into a final document?

I could just create one large template and use conditionals to control the display of paragraphs/pages. However, I'm wondering if it's possible to, for example, use logic in the `Program.cs` or similar file to merge different templates as needed.

My scenario: I could have a full template with 10 parts. In many situations I may only need "x" of 10 of those parts (i.e., not all 10 parts). I'm wondering if I can control what parts need to be inserted into the final documents. So, I would consider having logic in the code to pick what I need from 10 separate templates and merging it into one final document.

Currently, I am using the former approach of using conditionals, but my template is a bit cumbersome.

**Comment by autukill** [comment]
@remesq 
I've done this, and I made a document generation platform!
You can use [Open-Xml-PowerTools](https://github.com/OpenXmlDev/Open-Xml-PowerTools) to combine docs
![QQ截图20220917223647](https://user-images.githubusercontent.com/5186639/190863238-88ad3d19-4b42-4fc4-bdfd-7fef7fde1d9c.png)


@jarodsmk 
`a generic header and footer` this is same above, you could use Open-Xml-PowerTools, It can [handle header and footer](https://github.com/OpenXmlDev/Open-Xml-PowerTools/blob/vNext/OpenXmlPowerTools/DocumentBuilder.cs#L435).

**Comment by egonl** [comment]
Combining documents is not supported by SharpDocx, I would also use Open-Xml-PowerTools for this.
