### ISSUE TITLE
Unintended change from italic to bold in generated document

### ISSUE THREAD

**Issue by reiner-leu** [egonl/SharpDocx#48]
Hi egonl,
first of all thanks for your work!

I have a problem with following fragment:

<%=Model.Vorname%> <%=Model.Nachname%>
geboren am <%=Model.GebDatum%> in <%=Model.GebOrt%> <%=Model.GebLand%>)
  _<%=Model.GebDatumEn%> in <%=Model.GebOrtEn%> (<%=Model.GebLandEn%>)_

where the last line is in italic (and a smaller font size) in the template docx. 
Font: Frutiger LT Pro 45 Light, size 12 / 10

The processed part in the resulting docx is:
Nico Mustermann
geboren am 16.06.1970 in Göppingen (Deutschland)
  _1970-06-16 in Göppingen_ **(Germany)**
where date and city is printed italic, but "(Germany)" is printed bold in deed, respectively the font of this part has changed to 
MinionPro-Regular size 12 in the resulting docx.

I observed a similar behavior on the closing bracket in the 'German' line, which was  bolder than in the template, but this vanished with updating from 2.0.? to the recent version 2.2.0. 
Probably a similar reason?

**Comment by egonl** [comment]
Could you post an example project (zip or git)?

**Comment by reiner-leu** [comment]
Thanks for careing.
The problem is that the code is part of a web service with database access and so on, it would take some time to tailor it to a sdand alone project.
Trying a bit I found out the change of the font was depending on the blanks between the words, deleting all blanks showed the line in the expected form. Filling in the blanks again moved the problem to the end of the line 
- born <%=Model.GebDatumEn%> in <%=Model.GebOrtEn%> (<%=Model.GebLandEn%>) -
changing only the font of closing bracket. 
When I change the font size of the preceding '>' from 10 to 8 the bracket gets shown in the correct font and size.

Somehow the behavior reminds me of the bad old days before word utilized the xml structure, when a lot of inactive or deleted/hidden characters where within the document.

**Comment by egonl** [comment]
Glad you could resolve it!

Internally SharpDocx will remove anything in code blocks (anything between <% and %>).  If a code block contains a style change, it will get lost, leading to unexpected results. You can check for formatting using the *Reveal Formatting* pane in Word (Shift + F1).

**Comment by reiner-leu** [comment]
The funny thing is: there was no visible style change within the whole line.  (anyway, I did not use 'reveal formatting')
The problem disappeared only when introducing one (on the last closing '>') and reverting it on the last ')'.
Cheers,
Rainer
