### ISSUE TITLE
Update table of contents

### ISSUE THREAD

**Issue by vwegert** [egonl/SharpDocx#57]
Is it possible to automatically update the table of contents, list of tables/figures or similar features after generating the document? At the moment, we need to open the file manually and press Ctrl+A, F9 to update all generated parts; it would be great if we could automate this.

**Comment by egonl** [comment]
That's quite difficult, I think. The table of contents are actually Word fields which gets processed by Word. You could try to implement similar processing, but SharpDocx can't help you with that. You'll need to use the Open XML SDK directly for that.

Also, if you want to show page numbers in the TOC, you need to render the pages to determine the right page number. That's also something SharpDocx doesn't support. But you could try to use Word automation for this - if you really want it.

**Comment by vwegert** [comment]
Understood - I'll probably check whether the MS Office Interop assemblies are available and use them to update the TOC then.
