### ISSUE TITLE
Images inside if() block

### ISSUE THREAD

**Issue by monnster** [egonl/SharpDocx#59]
Hi!
I want to show different images, depending on flags in my model. All images have different size, so it's more convenient to scale it in Word template and surround with if() statements.
However, the generated document has no images, though the text from if() block is displayed.
How can I make so that images are also displayed in if() block without using Image() function?

**Comment by egonl** [comment]
Do you have an example view?

**Comment by egonl** [comment]
Since this is supported by using text blocks (see the Tutorial tomato) I guess wasn't using those.
