### ISSUE TITLE
SharpDocxV2 as nuget package?

### ISSUE THREAD

**Issue by weiterleiter1981** [egonl/SharpDocx#6]
Hi,

I have tested the V2 Branch and I did not find any issues by now. I am trying to reference the Project in my .net core solution, but there is SharpImage disturbing.

Somehow I cant get the project compiled after referencing it.

Is there a plan to provide a nuget package? Installation would be quite easy then.

**Comment by egonl** [comment]
v2 package is now available on nuget.org.
