### ISSUE TITLE
Is this project maintained and production ready ?

### ISSUE THREAD

**Issue by pada57** [egonl/SharpDocx#62]
As analyzing solution for document generation i would like to know if this project is actively maintained as i only see a release last January.

Can we base an enterprise solution on this lib ? if yes do you know who is using it ?

**Comment by egonl** [comment]
SharpDocx is being maintained and can be used for production. As far as I know it doesn't have any serious bugs, and if you happen to find one I'll look into it. However, I won't be doing any feature requests atm.
