### ISSUE TITLE
[Feature request] Send template as Stream

### ISSUE THREAD

**Issue by alphamax** [egonl/SharpDocx#63]
Hello,

I am testing SharpDocx and for my project, it could be useful to have a **stream** on "DocumentFactory.Create" instead of a path.
Do you accept a PR where I expose another DocumentFactory.Create that take a stream ?
What is needed/mandatory for this PR ? (stylecop or CI/CD) ?

Thanks,

B.

**Comment by egonl** [comment]
Sure, you can create a PR and I'll be more than happy to have a look at it. Nothing is mandatory, but it would be nice if it follows the current coding style and passes the build.

**Comment by egonl** [comment]
Added in #69 and released in version 2.5.0
