### ISSUE TITLE
Issue with nested if and formatted text in v2

### ISSUE THREAD

**Issue by somethingwithcode** [egonl/SharpDocx#7]
Hi,
I've run into an issue when using two if-statements with formatted text inbetween. I've used the example from Tutorial.cs.docx

`<% if (true) { %>This will also be displayed, but with formatting.<% } %>`

This works. If I change it to this:

```
<% if (true) { %>
Write outer with formatting. 
<% if (true) { %>
Write inner with formatting. 
<% } } %>
```

I get the following output on the window: 
```
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei SharpDocx.CodeBlocks.TextBlock.GetBody(OpenXmlElement startText, OpenXmlElement endText)
   bei SharpDocx.CodeBlocks.TextBlock.Initialize()
   bei SharpDocx.CodeBlockBuilder.AddCodeBlocks(CharacterMap map)
   bei SharpDocx.CodeBlockBuilder..ctor(WordprocessingDocument package)
   bei SharpDocx.DocumentCompiler.Compile(String viewPath, String className, String baseClassName, Type modelType, List`1 usingDirectives, List`1 referencedAssemblies)
   bei SharpDocx.DocumentAssembly..ctor(String viewPath, Type baseClass, Type modelType)
   bei SharpDocx.DocumentFactory.Create(String viewPath, Object model, Type baseClassType, Boolean forceCompile)
   bei SharpDocx.Ide.Start(String viewPath, String documentPath, Object model, Type baseClassType, Action`1 initializeDocument)
```

This happens only in v2, with the current master this works fine.

**Comment by egonl** [comment]
In V2 loops and if-statements use templates. SharpDocx requires that templates have their own start and end elements. Your sample contains two templates: one for the outer if and one for the inner if. However, by writing 
```
<% } } %>
```
both templates share the same end element. And that's unsupported at the moment.
The fix is easy:
```
<% } %>
<% } %>
```
The tutorial does use this construct, but does not explain why.

**Comment by egonl** [comment]
Added a section 'Text block limitations' to the tutorial.
