### ISSUE TITLE
Method with parameters

### ISSUE THREAD

**Issue by mastertnt** [egonl/SharpDocx#71]
Hi,

I am trying to use your nice library. Is it possible to call a method on object and pass some parameters ?

I didn't find how to pass a string to the method ? A method with no parameter works well.

Thx

**Comment by egonl** [comment]
The Tutorial shows some examples of calling methods with parameters, e.g. `<%= DateTime.Now.ToString("MMMM yyyy", System.Globalization.CultureInfo.InvariantCulture) %>`. Or do you mean something else?

**Comment by mastertnt** [comment]
No it is ok with a copy paste from an IDE probably i got a problem when i type directly the quote in WORD.

Thanks
