### ISSUE TITLE
Processing a HTML block

### ISSUE THREAD

**Issue by AudriusBartkus** [egonl/SharpDocx#77]
I'm looking for a way to output a html block, which is coming from rich text input field (similar to one for putting in this description) and can contain text formatting, links, images, tables, etc.
I understand that converting html to word is a difficult task and I will likely need to accept some limitations, and my attempts so far to do it were not too successful, so I'd like to hear if anyone had any success in doing something like this, or if there are any alternatives or recommendations when approaching this.

What I tried so far is: 
using HtmlAgilityPack to have more control over html elements and content. as a bare-bone solution I can split the html into elements and output text (using InnerText) and images. Text, however, loses all formatting.
I've tried creating custom formatting based on element type (for example bold for <b>), but I was only able to apply Bold styling to a whole paragraph and not individual line/word. (I tried setting RunProperties.Bold ). I also tried to add additional Paragraphs or Runs (that would have custom isolated styling) from withing my custom method, but with no success.

I was thinking of converting my custom function that takes description as a string <% ProcessHtmlBlock(fs.Description, imgScale); %> into foreach loop where I pass HtmlNode as an input instead. this would allow to apply some level of styling, but still not on 'per word' level. 

and then there's tables... no Idea how to even approach those. I've used them successfully as it is described in tutorial, but in this case everything is dynamic.

any tips, suggestions or personal experiences around any of this would be highly apreaciated

**Comment by paulsterling** [comment]
Hi @AudriusBartkus -

Just some comments that might help here. For sure what you want to do can be complex! Perhaps consider an existing project for this. I have looked at https://github.com/onizet/html2openxml in the past which does some HTML parsing and outputs OpenXml. You'd need to sort out how that works with the SharpDocx objects, but on first glance I think it's possible.

Another thought is to use an Html parsing library (ie, https://github.com/AngleSharp/AngleSharp) to create some type of known format that could then be used to creat the SharpDocx objects.

One other thought, once you have the HTML in a known format, you could directly create the Style Definitions like it's done in SharpDocx. Here's a gist with how we do that for some very specific styles (Bold and Red Text) that I plan to make more generic and submit a PR to SharpDocx for:  https://gist.github.com/paulsterling/23c0554704b4df50a6a2990544800c64

Hope that helps and I'll be following along.

**Comment by AudriusBartkus** [comment]
Hi @paulsterling, thank you for your comment! 
I've checked html2openxml before but thought the it and SharpDocx would be too imcompatable, but after you mentioned it - I tried it again and it worked extremely well out of the box. I'll try to upload better examples later on but simply running this gives pretty great result:
```
private IList<OpenXmlCompositeElement> ConvertHtmlToOpenXml(string htmlContent)
{
	HtmlConverter converter = new HtmlConverter(Package.MainDocumentPart);
	var parsedHtml = converter.Parse(htmlContent);
	return  parsedHtml;
}

protected void ProcessHtmlBlock(string value)
{
	if (string.IsNullOrWhiteSpace(value))
	{
		return;
	}

	var openXmlElements = ConvertHtmlToOpenXml(value);
	FixImageElements(openXmlElements);

	CurrentCodeBlock.Placeholder.Text = "\u200B";
	OpenXmlElement currentElement = CurrentCodeBlock.Placeholder;
	Paragraph refParagraph = CurrentCodeBlock.Placeholder.GetParent<Paragraph>();

	foreach (var element in openXmlElements)
	{
		if (element.GetType() == typeof(Paragraph))
		{
			refParagraph.InsertAfterSelf(element);
			refParagraph = (Paragraph)element;
		}
		else
		{
			Paragraph p =new Paragraph(new Run(element));
			refParagraph.InsertAfterSelf(p);
			refParagraph = p;
		}

	}
}
```
I've also checked your Bold and Red method examples, they helped me understand better how styling configuration works. For my use case, I updated  it a bit from creating new Paragraph to instead just creating a Run, as I needed to update inline text and full paragraphs. But for now I parked this approach to focus more on html2openxml one

**Comment by AudriusBartkus** [comment]
adding my HTML block processing implementation (using HtmlToOpenXml library), maybe it will be useful to someone. 
https://gist.github.com/AudriusBartkus/60bd87c87efdb6069455f906249ccac3
There's some additional methods for image processing (I wanted images to fit the page or be half page height tops)

**Comment by egon-das** [comment]
Hi @AudriusBartkus , that CustomDocument looks nice! Do you also have a view to play with?

**Comment by egonl** [comment]
Hi @AudriusBartkus, that CustomDocument looks nice! Do you also have a view to play with?

**Comment by AudriusBartkus** [comment]
> Hi @AudriusBartkus, that CustomDocument looks nice! Do you also have a view to play with?

Thanks! I can't share full solution unfortunately, but a simplified version would be:
viewModel:
```
	public class CustomViewModel
	{
                public int imgScale { get; set; }
                public List<WorkItemViewModel> wiList { get; set; }
		public class WorkItemViewModel
		{
			public string? WorkItemId { get; set; }
                        public string? WorkItemTitle { get; set; }
                        public string? Description { get; set; }
                }
        }
```
template.cs.docx:
```
<% int imgScale = Model.imgScale; %>

<% foreach (var wi in Model.wiList) { %>
<%=wi.WorkItemTitle%>
ID: <%=wi.WorkItemId%>
Description: 
<% ProcessHtmlBlock(wi.Description, imgScale); %>
 
<% } %>
```

My data is coming from Azure DevOps work items, but I guess any text-based html block would work for testing. I also update description imgs to have base64 data to simplify img processing (I know SharpDocx can manage imgs from link or file, I just found this easiest).
hope that helps!
