### ISSUE TITLE
All blank lines inside foreach are removed

### ISSUE THREAD

**Issue by garydewittjd** [egonl/SharpDocx#78]
All blank lines inside a foreach loop are removed. Outside the foreach, the blank lines are preserved.

If I put a space or tab in the blank line, the lines are preserved.

Is this normal behavior?

VIEW (all single spaced with not space after a line):

Test before blank link

After blank line, before foreach

<% foreach(var item in Model.families) { %>

September 22, 2024

<%=item.Name%>
<%=item.Address%>
<%=item.City%>, <%=item.State%> <%=item.Zip%>

Salutation here:

Before Blank Line

After Blank Line

<% } %>

OUTPUT:

Test before blank link

After blank line, before foreach

September 22, 2024
Joe Fred Dead
,  
Salutation here:
Before Blank Line
After Blank Line

**Comment by egonl** [comment]
Empty paragraphs in code blocks are indeed removed. This is done to prevent empty paragraphs where the code was stored. See https://github.com/egonl/SharpDocx/blob/96d0b9c4700e0e3824a22c5a95e06edf6659c592/SharpDocx/DocumentBase.cs#L155.

If you don't want this, leave a space or something like that in the paragraphs.
